import type { BankTriviaQuestion } from './types';

export const generalKnowledgeQuestions: BankTriviaQuestion[] = [
  {
    id: 'gk-e01',
    category: 'general_knowledge',
    difficulty: 'easy',
    question: 'How many days are in a leap year?',
    options: ['364', '365', '366', '367'],
    correctIndex: 2,
  },
  {
    id: 'gk-e02',
    category: 'general_knowledge',
    difficulty: 'easy',
    question: 'Which planet is known as the Red Planet?',
    options: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
    correctIndex: 1,
  },
  {
    id: 'gk-e03',
    category: 'general_knowledge',
    difficulty: 'easy',
    question: 'What is the largest ocean on Earth?',
    options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
    correctIndex: 3,
  },
  {
    id: 'gk-e04',
    category: 'general_knowledge',
    difficulty: 'easy',
    question: 'How many sides does a triangle have?',
    options: ['2', '3', '4', '5'],
    correctIndex: 1,
  },
  {
    id: 'gk-e05',
    category: 'general_knowledge',
    difficulty: 'easy',
    question: 'Which color do you get by mixing red and blue?',
    options: ['Green', 'Orange', 'Purple', 'Yellow'],
    correctIndex: 2,
  },
  {
    id: 'gk-e06',
    category: 'general_knowledge',
    difficulty: 'easy',
    question: 'What is the boiling point of water at sea level (°C)?',
    options: ['90', '100', '110', '120'],
    correctIndex: 1,
  },
  {
    id: 'gk-e07',
    category: 'general_knowledge',
    difficulty: 'easy',
    question: 'How many letters are in the English alphabet?',
    options: ['24', '25', '26', '27'],
    correctIndex: 2,
  },
  {
    id: 'gk-e08',
    category: 'general_knowledge',
    difficulty: 'easy',
    question: 'Which animal is known as the “King of the Jungle”?',
    options: ['Tiger', 'Lion', 'Bear', 'Elephant'],
    correctIndex: 1,
  },
  {
    id: 'gk-e09',
    category: 'general_knowledge',
    difficulty: 'easy',
    question: 'What do bees produce?',
    options: ['Milk', 'Silk', 'Honey', 'Wax only'],
    correctIndex: 2,
  },
  {
    id: 'gk-e10',
    category: 'general_knowledge',
    difficulty: 'easy',
    question: 'Which shape has four equal sides and four right angles?',
    options: ['Rhombus', 'Square', 'Trapezoid', 'Kite'],
    correctIndex: 1,
  },
  {
    id: 'gk-e11',
    category: 'general_knowledge',
    difficulty: 'easy',
    question: 'What is the smallest prime number?',
    options: ['0', '1', '2', '3'],
    correctIndex: 2,
  },
  {
    id: 'gk-e12',
    category: 'general_knowledge',
    difficulty: 'easy',
    question: 'Which month has 28 days in a common year?',
    options: ['February', 'April', 'June', 'All of them'],
    correctIndex: 3,
  },
  {
    id: 'gk-m01',
    category: 'general_knowledge',
    difficulty: 'medium',
    question: 'Who painted the ceiling of the Sistine Chapel?',
    options: ['Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Donatello'],
    correctIndex: 1,
  },
  {
    id: 'gk-m02',
    category: 'general_knowledge',
    difficulty: 'medium',
    question: 'What is the chemical symbol for gold?',
    options: ['Go', 'Gd', 'Au', 'Ag'],
    correctIndex: 2,
  },
  {
    id: 'gk-m03',
    category: 'general_knowledge',
    difficulty: 'medium',
    question: 'Which composer wrote the Four Seasons?',
    options: ['Bach', 'Handel', 'Vivaldi', 'Mozart'],
    correctIndex: 2,
  },
  {
    id: 'gk-m04',
    category: 'general_knowledge',
    difficulty: 'medium',
    question: 'What is the hardest natural substance on Earth?',
    options: ['Steel', 'Diamond', 'Granite', 'Titanium'],
    correctIndex: 1,
  },
  {
    id: 'gk-m05',
    category: 'general_knowledge',
    difficulty: 'medium',
    question: 'In which country would you find Machu Picchu?',
    options: ['Chile', 'Bolivia', 'Peru', 'Ecuador'],
    correctIndex: 2,
  },
  {
    id: 'gk-m06',
    category: 'general_knowledge',
    difficulty: 'medium',
    question: 'What is the largest mammal in the world?',
    options: ['African elephant', 'Blue whale', 'Giraffe', 'Hippo'],
    correctIndex: 1,
  },
  {
    id: 'gk-m07',
    category: 'general_knowledge',
    difficulty: 'medium',
    question: 'Which blood type is known as the universal donor?',
    options: ['A+', 'B+', 'AB+', 'O−'],
    correctIndex: 3,
  },
  {
    id: 'gk-m08',
    category: 'general_knowledge',
    difficulty: 'medium',
    question: 'What is the speed of light in vacuum (approx.)?',
    options: ['300,000 km/s', '150,000 km/s', '1,000 km/s', '3,000 km/s'],
    correctIndex: 0,
  },
  {
    id: 'gk-m09',
    category: 'general_knowledge',
    difficulty: 'medium',
    question: 'Which instrument has keys, pedals, and strings struck by hammers?',
    options: ['Harp', 'Organ', 'Piano', 'Celesta'],
    correctIndex: 2,
  },
  {
    id: 'gk-m10',
    category: 'general_knowledge',
    difficulty: 'medium',
    question: 'What is the main gas in Earth’s atmosphere?',
    options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Argon'],
    correctIndex: 2,
  },
  {
    id: 'gk-m11',
    category: 'general_knowledge',
    difficulty: 'medium',
    question: 'Which desert is the largest hot desert in the world?',
    options: ['Gobi', 'Kalahari', 'Sahara', 'Arabian'],
    correctIndex: 2,
  },
  {
    id: 'gk-h01',
    category: 'general_knowledge',
    difficulty: 'hard',
    question: 'Who wrote Crime and Punishment?',
    options: ['Tolstoy', 'Dostoevsky', 'Chekhov', 'Turgenev'],
    correctIndex: 1,
  },
  {
    id: 'gk-h02',
    category: 'general_knowledge',
    difficulty: 'hard',
    question: 'What is the SI unit of electric capacitance?',
    options: ['Ohm', 'Henry', 'Farad', 'Siemens'],
    correctIndex: 2,
  },
  {
    id: 'gk-h03',
    category: 'general_knowledge',
    difficulty: 'hard',
    question: 'Which philosopher wrote The Republic?',
    options: ['Aristotle', 'Plato', 'Socrates', 'Epicurus'],
    correctIndex: 1,
  },
  {
    id: 'gk-h04',
    category: 'general_knowledge',
    difficulty: 'hard',
    question: 'What is the approximate value of the golden ratio φ?',
    options: ['1.414', '1.618', '2.718', '3.142'],
    correctIndex: 1,
  },
  {
    id: 'gk-h05',
    category: 'general_knowledge',
    difficulty: 'hard',
    question: 'Which particle carries a negative charge in an atom?',
    options: ['Proton', 'Neutron', 'Electron', 'Positron'],
    correctIndex: 2,
  },
  {
    id: 'gk-h06',
    category: 'general_knowledge',
    difficulty: 'hard',
    question: 'In music theory, how many sharps are in the key signature of E major?',
    options: ['2', '3', '4', '5'],
    correctIndex: 2,
  },
  {
    id: 'gk-h07',
    category: 'general_knowledge',
    difficulty: 'hard',
    question: 'Which architect designed the Sydney Opera House?',
    options: ['Frank Gehry', 'Jørn Utzon', 'Zaha Hadid', 'Norman Foster'],
    correctIndex: 1,
  },
  {
    id: 'gk-h08',
    category: 'general_knowledge',
    difficulty: 'hard',
    question: 'What is the longest river in South America?',
    options: ['Paraná', 'Orinoco', 'Amazon', 'Magdalena'],
    correctIndex: 2,
  },
  {
    id: 'gk-h09',
    category: 'general_knowledge',
    difficulty: 'hard',
    question: 'Which vitamin is primarily produced in human skin via sunlight?',
    options: ['A', 'C', 'D', 'K'],
    correctIndex: 2,
  },
  {
    id: 'gk-h10',
    category: 'general_knowledge',
    difficulty: 'hard',
    question: 'What is the capital city of Mongolia?',
    options: ['Astana', 'Ulaanbaatar', 'Tashkent', 'Bishkek'],
    correctIndex: 1,
  },
  {
    id: 'gk-h11',
    category: 'general_knowledge',
    difficulty: 'hard',
    question: 'Which gas makes up most of the Sun by mass?',
    options: ['Helium', 'Oxygen', 'Hydrogen', 'Carbon'],
    correctIndex: 2,
  },
];
