import type { BankTriviaQuestion } from './types';

export const geographyQuestions: BankTriviaQuestion[] = [
  {
    id: 'geo-e01',
    category: 'geography',
    difficulty: 'easy',
    question: 'What is the capital of France?',
    options: ['Lyon', 'Paris', 'Marseille', 'Nice'],
    correctIndex: 1,
  },
  {
    id: 'geo-e02',
    category: 'geography',
    difficulty: 'easy',
    question: 'Which river runs through Egypt?',
    options: ['Amazon', 'Nile', 'Congo', 'Zambezi'],
    correctIndex: 1,
  },
  {
    id: 'geo-e03',
    category: 'geography',
    difficulty: 'easy',
    question: 'What is the largest country by land area?',
    options: ['Canada', 'China', 'USA', 'Russia'],
    correctIndex: 3,
  },
  {
    id: 'geo-e04',
    category: 'geography',
    difficulty: 'easy',
    question: 'Which continent is the Sahara Desert located on?',
    options: ['Asia', 'Africa', 'Australia', 'South America'],
    correctIndex: 1,
  },
  {
    id: 'geo-e05',
    category: 'geography',
    difficulty: 'easy',
    question: 'What is the capital of Japan?',
    options: ['Osaka', 'Kyoto', 'Tokyo', 'Hiroshima'],
    correctIndex: 2,
  },
  {
    id: 'geo-e06',
    category: 'geography',
    difficulty: 'easy',
    question: 'Which ocean lies between Africa and Australia?',
    options: ['Atlantic', 'Pacific', 'Indian', 'Arctic'],
    correctIndex: 2,
  },
  {
    id: 'geo-e07',
    category: 'geography',
    difficulty: 'easy',
    question: 'What is the smallest country in the world by area?',
    options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'],
    correctIndex: 1,
  },
  {
    id: 'geo-e08',
    category: 'geography',
    difficulty: 'easy',
    question: 'Which mountain range separates Europe from Asia in Russia?',
    options: ['Alps', 'Andes', 'Urals', 'Himalayas'],
    correctIndex: 2,
  },
  {
    id: 'geo-e09',
    category: 'geography',
    difficulty: 'easy',
    question: 'What is the capital of Australia?',
    options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
    correctIndex: 2,
  },
  {
    id: 'geo-e10',
    category: 'geography',
    difficulty: 'easy',
    question: 'Which country is shaped like a boot?',
    options: ['Greece', 'Italy', 'Spain', 'Croatia'],
    correctIndex: 1,
  },
  {
    id: 'geo-e11',
    category: 'geography',
    difficulty: 'easy',
    question: 'What is the longest river in Africa?',
    options: ['Congo', 'Nile', 'Niger', 'Zambezi'],
    correctIndex: 1,
  },
  {
    id: 'geo-m01',
    category: 'geography',
    difficulty: 'medium',
    question: 'Which strait separates Europe from Africa at Gibraltar?',
    options: ['Bosporus', 'Strait of Gibraltar', 'Dardanelles', 'English Channel'],
    correctIndex: 1,
  },
  {
    id: 'geo-m02',
    category: 'geography',
    difficulty: 'medium',
    question: 'What is the capital of Canada?',
    options: ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'],
    correctIndex: 2,
  },
  {
    id: 'geo-m03',
    category: 'geography',
    difficulty: 'medium',
    question: 'Lake Victoria is bordered by which three countries?',
    options: [
      'Kenya, Uganda, Tanzania',
      'Ethiopia, Sudan, Egypt',
      'Zambia, Zimbabwe, Botswana',
      'Rwanda, Burundi, DRC only',
    ],
    correctIndex: 0,
  },
  {
    id: 'geo-m04',
    category: 'geography',
    difficulty: 'medium',
    question: 'Which desert is the largest in Asia?',
    options: ['Gobi', 'Thar', 'Arabian', 'Taklamakan'],
    correctIndex: 0,
  },
  {
    id: 'geo-m05',
    category: 'geography',
    difficulty: 'medium',
    question: 'What is the highest mountain above sea level?',
    options: ['K2', 'Mount Everest', 'Kangchenjunga', 'Lhotse'],
    correctIndex: 1,
  },
  {
    id: 'geo-m06',
    category: 'geography',
    difficulty: 'medium',
    question: 'Which country has the most time zones (including territories)?',
    options: ['Russia', 'USA', 'France', 'Canada'],
    correctIndex: 2,
  },
  {
    id: 'geo-m07',
    category: 'geography',
    difficulty: 'medium',
    question: 'The city of Istanbul spans two continents: Europe and…',
    options: ['Africa', 'Asia', 'Australia', 'Antarctica'],
    correctIndex: 1,
  },
  {
    id: 'geo-m08',
    category: 'geography',
    difficulty: 'medium',
    question: 'Which African country was formerly known as Abyssinia?',
    options: ['Sudan', 'Ethiopia', 'Eritrea', 'Somalia'],
    correctIndex: 1,
  },
  {
    id: 'geo-m09',
    category: 'geography',
    difficulty: 'medium',
    question: 'What is the capital of New Zealand?',
    options: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'],
    correctIndex: 1,
  },
  {
    id: 'geo-m10',
    category: 'geography',
    difficulty: 'medium',
    question: 'Which sea separates Saudi Arabia from Africa?',
    options: ['Caspian Sea', 'Red Sea', 'Black Sea', 'Aral Sea'],
    correctIndex: 1,
  },
  {
    id: 'geo-m11',
    category: 'geography',
    difficulty: 'medium',
    question: 'Which river forms part of the border between the USA and Mexico?',
    options: ['Colorado', 'Rio Grande', 'Missouri', 'Columbia'],
    correctIndex: 1,
  },
  {
    id: 'geo-m12',
    category: 'geography',
    difficulty: 'medium',
    question: 'Madagascar lies off the coast of which continent?',
    options: ['Asia', 'Africa', 'South America', 'Australia'],
    correctIndex: 1,
  },
  {
    id: 'geo-h01',
    category: 'geography',
    difficulty: 'hard',
    question: 'Which country is completely surrounded by South Africa?',
    options: ['Eswatini', 'Lesotho', 'Botswana', 'Zimbabwe'],
    correctIndex: 1,
  },
  {
    id: 'geo-h02',
    category: 'geography',
    difficulty: 'hard',
    question: 'What is the deepest known point in Earth’s oceans?',
    options: ['Puerto Rico Trench', 'Mariana Trench', 'Java Trench', 'Tonga Trench'],
    correctIndex: 1,
  },
  {
    id: 'geo-h03',
    category: 'geography',
    difficulty: 'hard',
    question: 'Which two countries share the longest international land border?',
    options: ['USA–Mexico', 'Russia–Kazakhstan', 'Canada–USA', 'India–China'],
    correctIndex: 2,
  },
  {
    id: 'geo-h04',
    category: 'geography',
    difficulty: 'hard',
    question: 'The Danube River empties into which body of water?',
    options: ['Adriatic Sea', 'Black Sea', 'Caspian Sea', 'Aegean Sea'],
    correctIndex: 1,
  },
  {
    id: 'geo-h05',
    category: 'geography',
    difficulty: 'hard',
    question: 'Which Central American country does not border both oceans?',
    options: ['Panama', 'Costa Rica', 'Nicaragua', 'Belize'],
    correctIndex: 3,
  },
  {
    id: 'geo-h06',
    category: 'geography',
    difficulty: 'hard',
    question: 'What is the capital of Kazakhstan (as of the 1990s move)?',
    options: ['Almaty', 'Astana (Nur-Sultan)', 'Shymkent', 'Karaganda'],
    correctIndex: 1,
  },
  {
    id: 'geo-h07',
    category: 'geography',
    difficulty: 'hard',
    question: 'Which island nation is the world’s lowest average elevation?',
    options: ['Maldives', 'Tuvalu', 'Kiribati', 'Marshall Islands'],
    correctIndex: 0,
  },
  {
    id: 'geo-h08',
    category: 'geography',
    difficulty: 'hard',
    question: 'The Horn of Africa principally includes Somalia, Djibouti, Eritrea, and…',
    options: ['Kenya', 'Ethiopia', 'Sudan', 'Uganda'],
    correctIndex: 1,
  },
  {
    id: 'geo-h09',
    category: 'geography',
    difficulty: 'hard',
    question: 'Which European microstate is landlocked by Italy?',
    options: ['Monaco', 'San Marino', 'Liechtenstein', 'Andorra'],
    correctIndex: 1,
  },
  {
    id: 'geo-h10',
    category: 'geography',
    difficulty: 'hard',
    question: 'Lake Baikal is located in which country?',
    options: ['Mongolia', 'Russia', 'Kazakhstan', 'China'],
    correctIndex: 1,
  },
];
