import type { BankTriviaQuestion } from './types';

export const historyQuestions: BankTriviaQuestion[] = [
  {
    id: 'hi-e01',
    category: 'history',
    difficulty: 'easy',
    question: 'In which year did World War II end in Europe (V-E Day year)?',
    options: ['1943', '1944', '1945', '1946'],
    correctIndex: 2,
  },
  {
    id: 'hi-e02',
    category: 'history',
    difficulty: 'easy',
    question: 'Who was the first President of the United States?',
    options: ['Thomas Jefferson', 'George Washington', 'John Adams', 'Benjamin Franklin'],
    correctIndex: 1,
  },
  {
    id: 'hi-e03',
    category: 'history',
    difficulty: 'easy',
    question: 'Which ancient wonder was a lighthouse near Alexandria?',
    options: ['Colossus of Rhodes', 'Lighthouse of Alexandria', 'Hanging Gardens', 'Temple of Artemis'],
    correctIndex: 1,
  },
  {
    id: 'hi-e04',
    category: 'history',
    difficulty: 'easy',
    question: 'The Berlin Wall fell in which year?',
    options: ['1979', '1985', '1989', '1993'],
    correctIndex: 2,
  },
  {
    id: 'hi-e05',
    category: 'history',
    difficulty: 'easy',
    question: 'Who was known as the “Maid of Orléans”?',
    options: ['Catherine de’ Medici', 'Joan of Arc', 'Eleanor of Aquitaine', 'Marie Antoinette'],
    correctIndex: 1,
  },
  {
    id: 'hi-e06',
    category: 'history',
    difficulty: 'easy',
    question: 'Which empire built the Colosseum in Rome?',
    options: ['Byzantine Empire', 'Roman Empire', 'Ottoman Empire', 'Holy Roman Empire'],
    correctIndex: 1,
  },
  {
    id: 'hi-e07',
    category: 'history',
    difficulty: 'easy',
    question: 'The Titanic sank in which year?',
    options: ['1905', '1912', '1918', '1925'],
    correctIndex: 1,
  },
  {
    id: 'hi-e08',
    category: 'history',
    difficulty: 'easy',
    question: 'Who painted the Mona Lisa?',
    options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Caravaggio'],
    correctIndex: 1,
  },
  {
    id: 'hi-e09',
    category: 'history',
    difficulty: 'easy',
    question: 'Which country was the first to put a human in space?',
    options: ['USA', 'Soviet Union', 'China', 'UK'],
    correctIndex: 1,
  },
  {
    id: 'hi-e10',
    category: 'history',
    difficulty: 'easy',
    question: 'The ancient Pyramids of Giza are in which country?',
    options: ['Iraq', 'Egypt', 'Sudan', 'Turkey'],
    correctIndex: 1,
  },
  {
    id: 'hi-e11',
    category: 'history',
    difficulty: 'easy',
    question: 'Which war was fought between the North and South in the United States?',
    options: ['Revolutionary War', 'Civil War', 'War of 1812', 'Spanish-American War'],
    correctIndex: 1,
  },
  {
    id: 'hi-m01',
    category: 'history',
    difficulty: 'medium',
    question: 'Who was the British Prime Minister for most of World War II?',
    options: ['Neville Chamberlain', 'Winston Churchill', 'Clement Attlee', 'Anthony Eden'],
    correctIndex: 1,
  },
  {
    id: 'hi-m02',
    category: 'history',
    difficulty: 'medium',
    question: 'In which year did the French Revolution begin with the storming of the Bastille?',
    options: ['1776', '1789', '1799', '1815'],
    correctIndex: 1,
  },
  {
    id: 'hi-m03',
    category: 'history',
    difficulty: 'medium',
    question: 'Which empire was ruled by Genghis Khan’s successors?',
    options: ['Roman Empire', 'Mongol Empire', 'Persian Empire', 'Maurya Empire'],
    correctIndex: 1,
  },
  {
    id: 'hi-m04',
    category: 'history',
    difficulty: 'medium',
    question: 'The Battle of Waterloo (1815) ended whose rule as French Emperor?',
    options: ['Louis XIV', 'Napoleon Bonaparte', 'Charles X', 'Robespierre'],
    correctIndex: 1,
  },
  {
    id: 'hi-m05',
    category: 'history',
    difficulty: 'medium',
    question: 'Which ship brought the Pilgrims to North America in 1620?',
    options: ['Santa Maria', 'Mayflower', 'Endeavour', 'Beagle'],
    correctIndex: 1,
  },
  {
    id: 'hi-m06',
    category: 'history',
    difficulty: 'medium',
    question: 'Who led India’s nonviolent movement for independence from Britain?',
    options: ['Jawaharlal Nehru', 'Mahatma Gandhi', 'Subhas Chandra Bose', 'B. R. Ambedkar'],
    correctIndex: 1,
  },
  {
    id: 'hi-m07',
    category: 'history',
    difficulty: 'medium',
    question: 'The Protestant Reformation is often linked to which figure?',
    options: ['John Calvin', 'Martin Luther', 'Henry VIII', 'Ignatius of Loyola'],
    correctIndex: 1,
  },
  {
    id: 'hi-m08',
    category: 'history',
    difficulty: 'medium',
    question: 'Which city was the capital of the Byzantine Empire?',
    options: ['Rome', 'Constantinople', 'Athens', 'Antioch'],
    correctIndex: 1,
  },
  {
    id: 'hi-m09',
    category: 'history',
    difficulty: 'medium',
    question: 'Who was the longest-reigning British monarch before Elizabeth II surpassed the record?',
    options: ['George III', 'Victoria', 'Henry VIII', 'James I'],
    correctIndex: 1,
  },
  {
    id: 'hi-m10',
    category: 'history',
    difficulty: 'medium',
    question: 'The Code of Hammurabi is associated with which region?',
    options: ['Ancient Egypt', 'Mesopotamia', 'Indus Valley', 'Ancient Greece'],
    correctIndex: 1,
  },
  {
    id: 'hi-m11',
    category: 'history',
    difficulty: 'medium',
    question: 'Which treaty ended World War I for Germany?',
    options: ['Treaty of Versailles', 'Treaty of Paris', 'Treaty of Tordesillas', 'Treaty of Utrecht'],
    correctIndex: 0,
  },
  {
    id: 'hi-m12',
    category: 'history',
    difficulty: 'medium',
    question: 'Who was the first Emperor of a unified China in the Qin dynasty?',
    options: ['Liu Bang', 'Qin Shi Huang', 'Wu Zetian', 'Kublai Khan'],
    correctIndex: 1,
  },
  {
    id: 'hi-h01',
    category: 'history',
    difficulty: 'hard',
    question: 'Which battle in 1066 led to Norman control of England?',
    options: ['Battle of Hastings', 'Battle of Bosworth', 'Battle of Agincourt', 'Battle of Naseby'],
    correctIndex: 0,
  },
  {
    id: 'hi-h02',
    category: 'history',
    difficulty: 'hard',
    question: 'The Congress of Vienna (1814–1815) aimed to reorganize Europe after whose defeat?',
    options: ['Napoleon', 'Ottoman Empire', 'Habsburgs', 'Russian Empire'],
    correctIndex: 0,
  },
  {
    id: 'hi-h03',
    category: 'history',
    difficulty: 'hard',
    question: 'Which empire was ruled by Cyrus the Great?',
    options: ['Roman', 'Achaemenid Persian', 'Assyrian', 'Macedonian'],
    correctIndex: 1,
  },
  {
    id: 'hi-h04',
    category: 'history',
    difficulty: 'hard',
    question: 'Who wrote The Communist Manifesto with Friedrich Engels?',
    options: ['Vladimir Lenin', 'Karl Marx', 'Joseph Stalin', 'Mikhail Bakunin'],
    correctIndex: 1,
  },
  {
    id: 'hi-h05',
    category: 'history',
    difficulty: 'hard',
    question: 'The Thirty Years’ War (1618–1648) was fought mainly in which region?',
    options: ['Balkans', 'Central Europe', 'Iberia', 'Scandinavia'],
    correctIndex: 1,
  },
  {
    id: 'hi-h06',
    category: 'history',
    difficulty: 'hard',
    question: 'Which African empire was led by Mansa Musa?',
    options: ['Ethiopian Empire', 'Mali Empire', 'Songhai Empire', 'Kingdom of Kongo'],
    correctIndex: 1,
  },
  {
    id: 'hi-h07',
    category: 'history',
    difficulty: 'hard',
    question: 'The Meiji Restoration began in which country in 1868?',
    options: ['China', 'Japan', 'Korea', 'Thailand'],
    correctIndex: 1,
  },
  {
    id: 'hi-h08',
    category: 'history',
    difficulty: 'hard',
    question: 'Which pharaoh’s tomb was discovered by Howard Carter in 1922?',
    options: ['Ramesses II', 'Tutankhamun', 'Akhenaten', 'Hatshepsut'],
    correctIndex: 1,
  },
  {
    id: 'hi-h09',
    category: 'history',
    difficulty: 'hard',
    question: 'The Peloponnesian War was fought between Athens and which rival league?',
    options: ['Persia', 'Sparta and allies', 'Macedon', 'Thebes only'],
    correctIndex: 1,
  },
  {
    id: 'hi-h10',
    category: 'history',
    difficulty: 'hard',
    question: 'Which 1215 charter limited the powers of the English king?',
    options: ['Bill of Rights', 'Magna Carta', 'Domesday Book', 'Act of Union'],
    correctIndex: 1,
  },
];
