import type { BankTriviaQuestion } from './types';

export const moviesTvQuestions: BankTriviaQuestion[] = [
  {
    id: 'mt-e01',
    category: 'movies_tv',
    difficulty: 'easy',
    question: 'Who played Jack in Titanic (1997)?',
    options: ['Brad Pitt', 'Leonardo DiCaprio', 'Tom Cruise', 'Matt Damon'],
    correctIndex: 1,
  },
  {
    id: 'mt-e02',
    category: 'movies_tv',
    difficulty: 'easy',
    question: 'What is the name of the kingdom in Disney’s Frozen?',
    options: ['Arendelle', 'Corona', 'DunBroch', 'Atlantica'],
    correctIndex: 0,
  },
  {
    id: 'mt-e03',
    category: 'movies_tv',
    difficulty: 'easy',
    question: 'Which sitcom features Central Perk café?',
    options: ['Seinfeld', 'Friends', 'The Office', 'Parks and Recreation'],
    correctIndex: 1,
  },
  {
    id: 'mt-e04',
    category: 'movies_tv',
    difficulty: 'easy',
    question: 'What is the name of the hobbit played by Elijah Wood in The Lord of the Rings?',
    options: ['Sam', 'Frodo', 'Pippin', 'Merry'],
    correctIndex: 1,
  },
  {
    id: 'mt-e05',
    category: 'movies_tv',
    difficulty: 'easy',
    question: 'Which animated series features Homer, Marge, Bart, Lisa, and Maggie?',
    options: ['Family Guy', 'The Simpsons', 'South Park', 'Bob’s Burgers'],
    correctIndex: 1,
  },
  {
    id: 'mt-e06',
    category: 'movies_tv',
    difficulty: 'easy',
    question: 'Who directed Jurassic Park (1993)?',
    options: ['James Cameron', 'Steven Spielberg', 'George Lucas', 'Ridley Scott'],
    correctIndex: 1,
  },
  {
    id: 'mt-e07',
    category: 'movies_tv',
    difficulty: 'easy',
    question: 'What is the name of the AI villain in 2001: A Space Odyssey?',
    options: ['HAL 9000', 'JARVIS', 'Skynet', 'Mother'],
    correctIndex: 0,
  },
  {
    id: 'mt-e08',
    category: 'movies_tv',
    difficulty: 'easy',
    question: 'Which film franchise features “May the Force be with you”?',
    options: ['Star Trek', 'Star Wars', 'Dune', 'The Matrix'],
    correctIndex: 1,
  },
  {
    id: 'mt-e09',
    category: 'movies_tv',
    difficulty: 'easy',
    question: 'What is the highest-grossing film of all time (unadjusted for inflation, typical box-office lists)?',
    options: ['Titanic', 'Avatar', 'Avengers: Endgame', 'Star Wars: The Force Awakens'],
    correctIndex: 1,
  },
  {
    id: 'mt-e10',
    category: 'movies_tv',
    difficulty: 'easy',
    question: 'Which British series stars Benedict Cumberbatch as a modern Sherlock Holmes?',
    options: ['Luther', 'Sherlock', 'Broadchurch', 'Line of Duty'],
    correctIndex: 1,
  },
  {
    id: 'mt-e11',
    category: 'movies_tv',
    difficulty: 'easy',
    question: 'In The Lion King, what type of animal is Timon?',
    options: ['Warthog', 'Meerkat', 'Monkey', 'Hyena'],
    correctIndex: 1,
  },
  {
    id: 'mt-m01',
    category: 'movies_tv',
    difficulty: 'medium',
    question: 'Who played the Joker in The Dark Knight (2008)?',
    options: ['Jared Leto', 'Heath Ledger', 'Jack Nicholson', 'Joaquin Phoenix'],
    correctIndex: 1,
  },
  {
    id: 'mt-m02',
    category: 'movies_tv',
    difficulty: 'medium',
    question: 'Which film won the first Academy Award for Best Picture?',
    options: ['Sunrise', 'Wings', 'Metropolis', 'The Jazz Singer'],
    correctIndex: 1,
  },
  {
    id: 'mt-m03',
    category: 'movies_tv',
    difficulty: 'medium',
    question: 'What is the fictional African country in Black Panther?',
    options: ['Zamunda', 'Wakanda', 'Genosha', 'Latveria'],
    correctIndex: 1,
  },
  {
    id: 'mt-m04',
    category: 'movies_tv',
    difficulty: 'medium',
    question: 'Who created Breaking Bad?',
    options: ['David Chase', 'Vince Gilligan', 'Matthew Weiner', 'David Simon'],
    correctIndex: 1,
  },
  {
    id: 'mt-m05',
    category: 'movies_tv',
    difficulty: 'medium',
    question: 'Which actress played Eleven in Stranger Things?',
    options: ['Sadie Sink', 'Millie Bobby Brown', 'Natalia Dyer', 'Winona Ryder'],
    correctIndex: 1,
  },
  {
    id: 'mt-m06',
    category: 'movies_tv',
    difficulty: 'medium',
    question: 'In The Matrix, what color pill does Neo take to learn the truth?',
    options: ['Blue', 'Red', 'Green', 'Yellow'],
    correctIndex: 1,
  },
  {
    id: 'mt-m07',
    category: 'movies_tv',
    difficulty: 'medium',
    question: 'Which director made Pulp Fiction (1994)?',
    options: ['Martin Scorsese', 'Quentin Tarantino', 'Coen Brothers', 'Spike Lee'],
    correctIndex: 1,
  },
  {
    id: 'mt-m08',
    category: 'movies_tv',
    difficulty: 'medium',
    question: 'What is the name of the coffee shop in Friends?',
    options: ['Monk’s', 'Central Perk', 'Luke’s', 'Café Nervosa'],
    correctIndex: 1,
  },
  {
    id: 'mt-m09',
    category: 'movies_tv',
    difficulty: 'medium',
    question: 'Which 1972 film is famous for “I’m gonna make him an offer he can’t refuse”?',
    options: ['Goodfellas', 'The Godfather', 'Scarface', 'Casino'],
    correctIndex: 1,
  },
  {
    id: 'mt-m10',
    category: 'movies_tv',
    difficulty: 'medium',
    question: 'Who played Tony Stark / Iron Man in the Marvel Cinematic Universe?',
    options: ['Chris Evans', 'Chris Hemsworth', 'Robert Downey Jr.', 'Mark Ruffalo'],
    correctIndex: 2,
  },
  {
    id: 'mt-m11',
    category: 'movies_tv',
    difficulty: 'medium',
    question: 'Which series is set in the Dunder Mifflin paper company?',
    options: ['Parks and Recreation', 'The Office (US)', 'Brooklyn Nine-Nine', 'Superstore'],
    correctIndex: 1,
  },
  {
    id: 'mt-m12',
    category: 'movies_tv',
    difficulty: 'medium',
    question: 'What year did the first episode of The Simpsons as a series air (approx.)?',
    options: ['1987', '1989', '1992', '1995'],
    correctIndex: 1,
  },
  {
    id: 'mt-h01',
    category: 'movies_tv',
    difficulty: 'hard',
    question: 'Which Alfred Hitchcock film features the Bates Motel?',
    options: ['Vertigo', 'Psycho', 'Rear Window', 'North by Northwest'],
    correctIndex: 1,
  },
  {
    id: 'mt-h02',
    category: 'movies_tv',
    difficulty: 'hard',
    question: 'Who composed the score for Star Wars (1977)?',
    options: ['Hans Zimmer', 'John Williams', 'Ennio Morricone', 'Danny Elfman'],
    correctIndex: 1,
  },
  {
    id: 'mt-h03',
    category: 'movies_tv',
    difficulty: 'hard',
    question: 'Which film is known for the line “Here’s Johnny!”?',
    options: ['The Exorcist', 'The Shining', 'Halloween', 'A Nightmare on Elm Street'],
    correctIndex: 1,
  },
  {
    id: 'mt-h04',
    category: 'movies_tv',
    difficulty: 'hard',
    question: 'In Citizen Kane, what is “Rosebud”?',
    options: ['A person', 'A sled', 'A newspaper', 'A house'],
    correctIndex: 1,
  },
  {
    id: 'mt-h05',
    category: 'movies_tv',
    difficulty: 'hard',
    question: 'Which Japanese director directed Seven Samurai (1954)?',
    options: ['Yasujirō Ozu', 'Akira Kurosawa', 'Kenji Mizoguchi', 'Hayao Miyazaki'],
    correctIndex: 1,
  },
  {
    id: 'mt-h06',
    category: 'movies_tv',
    difficulty: 'hard',
    question: 'What is the name of the fictional continent in Game of Thrones where most of the story takes place?',
    options: ['Essos', 'Westeros', 'Sothoryos', 'Ulthos'],
    correctIndex: 1,
  },
  {
    id: 'mt-h07',
    category: 'movies_tv',
    difficulty: 'hard',
    question: 'Which actress won an Oscar for playing Margaret Thatcher in The Iron Lady?',
    options: ['Helen Mirren', 'Meryl Streep', 'Judi Dench', 'Cate Blanchett'],
    correctIndex: 1,
  },
  {
    id: 'mt-h08',
    category: 'movies_tv',
    difficulty: 'hard',
    question: 'In Blade Runner, what term describes bioengineered humans?',
    options: ['Synths', 'Replicants', 'Hosts', 'Clones'],
    correctIndex: 1,
  },
  {
    id: 'mt-h09',
    category: 'movies_tv',
    difficulty: 'hard',
    question: 'Which David Lynch TV series famously begins with “Who killed Laura Palmer?”',
    options: ['The X-Files', 'Twin Peaks', 'Lost', 'True Detective'],
    correctIndex: 1,
  },
  {
    id: 'mt-h10',
    category: 'movies_tv',
    difficulty: 'hard',
    question: 'Which silent film star was known as “The Tramp”?',
    options: ['Buster Keaton', 'Charlie Chaplin', 'Harold Lloyd', 'Rudolph Valentino'],
    correctIndex: 1,
  },
];
