import type { BankTriviaQuestion } from './types';

export const scienceTechnologyQuestions: BankTriviaQuestion[] = [
  {
    id: 'st-e01',
    category: 'science_technology',
    difficulty: 'easy',
    question: 'What does “WWW” stand for?',
    options: ['Wide Web World', 'World Wide Web', 'Web World Wide', 'Wireless Web Work'],
    correctIndex: 1,
  },
  {
    id: 'st-e02',
    category: 'science_technology',
    difficulty: 'easy',
    question: 'Which planet is closest to the Sun?',
    options: ['Venus', 'Earth', 'Mercury', 'Mars'],
    correctIndex: 2,
  },
  {
    id: 'st-e03',
    category: 'science_technology',
    difficulty: 'easy',
    question: 'What is H₂O commonly known as?',
    options: ['Salt', 'Water', 'Oxygen', 'Hydrogen peroxide'],
    correctIndex: 1,
  },
  {
    id: 'st-e04',
    category: 'science_technology',
    difficulty: 'easy',
    question: 'How many bones are in an adult human body (typical)?',
    options: ['186', '206', '226', '256'],
    correctIndex: 1,
  },
  {
    id: 'st-e05',
    category: 'science_technology',
    difficulty: 'easy',
    question: 'What force pulls objects toward Earth?',
    options: ['Magnetism', 'Friction', 'Gravity', 'Tension'],
    correctIndex: 2,
  },
  {
    id: 'st-e06',
    category: 'science_technology',
    difficulty: 'easy',
    question: 'Which company created the iPhone?',
    options: ['Google', 'Microsoft', 'Apple', 'Samsung'],
    correctIndex: 2,
  },
  {
    id: 'st-e07',
    category: 'science_technology',
    difficulty: 'easy',
    question: 'What is the center of an atom called?',
    options: ['Electron shell', 'Nucleus', 'Proton cloud', 'Neutron ring'],
    correctIndex: 1,
  },
  {
    id: 'st-e08',
    category: 'science_technology',
    difficulty: 'easy',
    question: 'Which gas do plants absorb from the atmosphere for photosynthesis?',
    options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Helium'],
    correctIndex: 2,
  },
  {
    id: 'st-e09',
    category: 'science_technology',
    difficulty: 'easy',
    question: 'What does “CPU” stand for?',
    options: [
      'Central Processing Unit',
      'Computer Personal Unit',
      'Core Power Utility',
      'Cached Program Uplink',
    ],
    correctIndex: 0,
  },
  {
    id: 'st-e10',
    category: 'science_technology',
    difficulty: 'easy',
    question: 'Which organ pumps blood through the body?',
    options: ['Liver', 'Lung', 'Heart', 'Kidney'],
    correctIndex: 2,
  },
  {
    id: 'st-e11',
    category: 'science_technology',
    difficulty: 'easy',
    question: 'What is the freezing point of water in Celsius?',
    options: ['−10 °C', '0 °C', '32 °C', '100 °C'],
    correctIndex: 1,
  },
  {
    id: 'st-e12',
    category: 'science_technology',
    difficulty: 'easy',
    question: 'Which programming language is often used for web browsers alongside HTML?',
    options: ['C++', 'Rust', 'JavaScript', 'Swift'],
    correctIndex: 2,
  },
  {
    id: 'st-m01',
    category: 'science_technology',
    difficulty: 'medium',
    question: 'What is the chemical formula for table salt?',
    options: ['NaCl', 'KCl', 'NaOH', 'HCl'],
    correctIndex: 0,
  },
  {
    id: 'st-m02',
    category: 'science_technology',
    difficulty: 'medium',
    question: 'Who proposed the theory of general relativity?',
    options: ['Isaac Newton', 'Albert Einstein', 'Niels Bohr', 'Max Planck'],
    correctIndex: 1,
  },
  {
    id: 'st-m03',
    category: 'science_technology',
    difficulty: 'medium',
    question: 'What is the powerhouse of the animal cell?',
    options: ['Nucleus', 'Ribosome', 'Mitochondrion', 'Golgi apparatus'],
    correctIndex: 2,
  },
  {
    id: 'st-m04',
    category: 'science_technology',
    difficulty: 'medium',
    question: 'Which planet has the Great Red Spot storm?',
    options: ['Saturn', 'Jupiter', 'Neptune', 'Uranus'],
    correctIndex: 1,
  },
  {
    id: 'st-m05',
    category: 'science_technology',
    difficulty: 'medium',
    question: 'What does “HTTP” stand for?',
    options: [
      'HyperText Transfer Protocol',
      'High Transfer Text Process',
      'Host Text Transmission Path',
      'Hyperlink Tracking Transport Packet',
    ],
    correctIndex: 0,
  },
  {
    id: 'st-m06',
    category: 'science_technology',
    difficulty: 'medium',
    question: 'Which particle has no electric charge?',
    options: ['Electron', 'Proton', 'Neutron', 'Positron'],
    correctIndex: 2,
  },
  {
    id: 'st-m07',
    category: 'science_technology',
    difficulty: 'medium',
    question: 'What is the speed of sound in air at room temperature (approx.)?',
    options: ['150 m/s', '343 m/s', '1,000 m/s', '3,000 m/s'],
    correctIndex: 1,
  },
  {
    id: 'st-m08',
    category: 'science_technology',
    difficulty: 'medium',
    question: 'Which blood cells fight infection?',
    options: ['Platelets', 'Red blood cells', 'White blood cells', 'Plasma'],
    correctIndex: 2,
  },
  {
    id: 'st-m09',
    category: 'science_technology',
    difficulty: 'medium',
    question: 'What is the binary number 1010 in decimal?',
    options: ['8', '9', '10', '12'],
    correctIndex: 2,
  },
  {
    id: 'st-m10',
    category: 'science_technology',
    difficulty: 'medium',
    question: 'DNA stands for…',
    options: [
      'Deoxyribonucleic acid',
      'Dynamic nucleotide assembly',
      'Dual neural algorithm',
      'Diatomic nitrogen acid',
    ],
    correctIndex: 0,
  },
  {
    id: 'st-m11',
    category: 'science_technology',
    difficulty: 'medium',
    question: 'Which layer of Earth is mostly liquid iron and nickel?',
    options: ['Crust', 'Mantle', 'Outer core', 'Inner core'],
    correctIndex: 2,
  },
  {
    id: 'st-h01',
    category: 'science_technology',
    difficulty: 'hard',
    question: 'What is the approximate age of the universe according to Planck 2018 results?',
    options: ['4.5 billion years', '13.8 billion years', '100 billion years', '1 billion years'],
    correctIndex: 1,
  },
  {
    id: 'st-h02',
    category: 'science_technology',
    difficulty: 'hard',
    question: 'Which scientist published On the Origin of Species?',
    options: ['Gregor Mendel', 'Charles Darwin', 'Alfred Wallace', 'Louis Pasteur'],
    correctIndex: 1,
  },
  {
    id: 'st-h03',
    category: 'science_technology',
    difficulty: 'hard',
    question: 'What is the Heisenberg uncertainty principle primarily about?',
    options: [
      'Energy and time cannot both be known exactly',
      'Position and momentum cannot both be known exactly',
      'Mass and volume trade off',
      'Electric and magnetic fields cancel',
    ],
    correctIndex: 1,
  },
  {
    id: 'st-h04',
    category: 'science_technology',
    difficulty: 'hard',
    question: 'Which algorithmic problem class does “P vs NP” refer to?',
    options: [
      'Polynomial time vs nondeterministic polynomial time',
      'Prime vs non-prime',
      'Parallel vs sequential',
      'Probabilistic vs quantum',
    ],
    correctIndex: 0,
  },
  {
    id: 'st-h05',
    category: 'science_technology',
    difficulty: 'hard',
    question: 'What is the half-life of carbon-14 (approx.)?',
    options: ['570 years', '5,730 years', '50,000 years', '1 million years'],
    correctIndex: 1,
  },
  {
    id: 'st-h06',
    category: 'science_technology',
    difficulty: 'hard',
    question: 'Which particle mediates the weak nuclear force (along with Z)?',
    options: ['Gluon', 'Photon', 'W boson', 'Graviton'],
    correctIndex: 2,
  },
  {
    id: 'st-h07',
    category: 'science_technology',
    difficulty: 'hard',
    question: 'What is the escape velocity from Earth’s surface (approx., km/s)?',
    options: ['4.2', '7.9', '11.2', '15.0'],
    correctIndex: 2,
  },
  {
    id: 'st-h08',
    category: 'science_technology',
    difficulty: 'hard',
    question: 'Who is credited with inventing the World Wide Web?',
    options: ['Vint Cerf', 'Tim Berners-Lee', 'Alan Turing', 'Linus Torvalds'],
    correctIndex: 1,
  },
  {
    id: 'st-h09',
    category: 'science_technology',
    difficulty: 'hard',
    question: 'What is the second law of thermodynamics most associated with?',
    options: ['Energy conservation', 'Entropy increase', 'Absolute zero', 'Wave-particle duality'],
    correctIndex: 1,
  },
  {
    id: 'st-h10',
    category: 'science_technology',
    difficulty: 'hard',
    question: 'Which pure metal is the best electrical conductor at room temperature?',
    options: ['Copper', 'Gold', 'Silver', 'Aluminum'],
    correctIndex: 2,
  },
  {
    id: 'st-h11',
    category: 'science_technology',
    difficulty: 'hard',
    question: 'What does a “qubit” represent in quantum computing?',
    options: [
      'A quantum bit of information',
      'A queued binary token',
      'A quick universal bus',
      'A quality assurance byte',
    ],
    correctIndex: 0,
  },
];
