import type { BankTriviaQuestion } from './types';

export const sportsQuestions: BankTriviaQuestion[] = [
  {
    id: 'sp-e01',
    category: 'sports',
    difficulty: 'easy',
    question: 'How many players are on a basketball team on the court at once?',
    options: ['4', '5', '6', '7'],
    correctIndex: 1,
  },
  {
    id: 'sp-e02',
    category: 'sports',
    difficulty: 'easy',
    question: 'In soccer, what is it called when a player scores three goals in one game?',
    options: ['Double', 'Hat-trick', 'Grand slam', 'Triple crown'],
    correctIndex: 1,
  },
  {
    id: 'sp-e03',
    category: 'sports',
    difficulty: 'easy',
    question: 'Which sport uses a racket and a shuttlecock?',
    options: ['Tennis', 'Squash', 'Badminton', 'Table tennis'],
    correctIndex: 2,
  },
  {
    id: 'sp-e04',
    category: 'sports',
    difficulty: 'easy',
    question: 'How many bases are there on a baseball diamond (including home)?',
    options: ['3', '4', '5', '6'],
    correctIndex: 1,
  },
  {
    id: 'sp-e05',
    category: 'sports',
    difficulty: 'easy',
    question: 'Which country hosted the 2016 Summer Olympics?',
    options: ['China', 'UK', 'Brazil', 'Russia'],
    correctIndex: 2,
  },
  {
    id: 'sp-e06',
    category: 'sports',
    difficulty: 'easy',
    question: 'In American football, how many points is a touchdown worth (before PAT)?',
    options: ['3', '6', '7', '8'],
    correctIndex: 1,
  },
  {
    id: 'sp-e07',
    category: 'sports',
    difficulty: 'easy',
    question: 'What color flag is waved in motorsport to mean “race stopped”?',
    options: ['Yellow', 'Green', 'Red', 'Black'],
    correctIndex: 2,
  },
  {
    id: 'sp-e08',
    category: 'sports',
    difficulty: 'easy',
    question: 'How long is a standard marathon (approx.)?',
    options: ['21 km', '42 km', '10 km', '50 km'],
    correctIndex: 1,
  },
  {
    id: 'sp-e09',
    category: 'sports',
    difficulty: 'easy',
    question: 'Which sport is played at Wimbledon?',
    options: ['Golf', 'Tennis', 'Cricket', 'Rugby'],
    correctIndex: 1,
  },
  {
    id: 'sp-e10',
    category: 'sports',
    difficulty: 'easy',
    question: 'In volleyball, how many hits per side are typically allowed before sending the ball over?',
    options: ['2', '3', '4', '5'],
    correctIndex: 1,
  },
  {
    id: 'sp-e11',
    category: 'sports',
    difficulty: 'easy',
    question: 'What is the name of basketball’s top professional league in North America?',
    options: ['NFL', 'MLB', 'NBA', 'NHL'],
    correctIndex: 2,
  },
  {
    id: 'sp-m01',
    category: 'sports',
    difficulty: 'medium',
    question: 'Who has won the most Formula 1 World Drivers’ Championships?',
    options: ['Ayrton Senna', 'Alain Prost', 'Lewis Hamilton', 'Sebastian Vettel'],
    correctIndex: 2,
  },
  {
    id: 'sp-m02',
    category: 'sports',
    difficulty: 'medium',
    question: 'In which year were the first modern Olympic Games held?',
    options: ['1886', '1896', '1906', '1916'],
    correctIndex: 1,
  },
  {
    id: 'sp-m03',
    category: 'sports',
    difficulty: 'medium',
    question: 'Which country won the FIFA World Cup in 2018?',
    options: ['Germany', 'Brazil', 'France', 'Argentina'],
    correctIndex: 2,
  },
  {
    id: 'sp-m04',
    category: 'sports',
    difficulty: 'medium',
    question: 'How many periods are in a standard NHL hockey game?',
    options: ['2', '3', '4', '5'],
    correctIndex: 1,
  },
  {
    id: 'sp-m05',
    category: 'sports',
    difficulty: 'medium',
    question: 'What is the maximum score with three darts on a standard dartboard (single bull)?',
    options: ['150', '170', '180', '200'],
    correctIndex: 2,
  },
  {
    id: 'sp-m06',
    category: 'sports',
    difficulty: 'medium',
    question: 'In cricket, how many runs is a “six” worth?',
    options: ['4', '5', '6', '10'],
    correctIndex: 2,
  },
  {
    id: 'sp-m07',
    category: 'sports',
    difficulty: 'medium',
    question: 'Which golfer has the most major championship wins (as of 2020)?',
    options: ['Arnold Palmer', 'Tiger Woods', 'Jack Nicklaus', 'Gary Player'],
    correctIndex: 2,
  },
  {
    id: 'sp-m08',
    category: 'sports',
    difficulty: 'medium',
    question: 'What distance is a full Ironman swim (approx.)?',
    options: ['1.9 km', '2.4 miles (3.86 km)', '5 km', '10 km'],
    correctIndex: 1,
  },
  {
    id: 'sp-m09',
    category: 'sports',
    difficulty: 'medium',
    question: 'Which NBA team plays its home games at Madison Square Garden?',
    options: ['Nets', 'Knicks', 'Celtics', '76ers'],
    correctIndex: 1,
  },
  {
    id: 'sp-m10',
    category: 'sports',
    difficulty: 'medium',
    question: 'In rugby union, how many points is a try worth?',
    options: ['3', '5', '7', '10'],
    correctIndex: 1,
  },
  {
    id: 'sp-m11',
    category: 'sports',
    difficulty: 'medium',
    question: 'Which country invented sumo wrestling as a professional sport tradition?',
    options: ['China', 'Korea', 'Japan', 'Mongolia'],
    correctIndex: 2,
  },
  {
    id: 'sp-m12',
    category: 'sports',
    difficulty: 'medium',
    question: 'In baseball, how many outs end a half-inning?',
    options: ['2', '3', '4', '5'],
    correctIndex: 1,
  },
  {
    id: 'sp-h01',
    category: 'sports',
    difficulty: 'hard',
    question: 'Who was the first athlete to run a sub-four-minute mile?',
    options: ['Sebastian Coe', 'Roger Bannister', 'Steve Ovett', 'John Landy'],
    correctIndex: 1,
  },
  {
    id: 'sp-h02',
    category: 'sports',
    difficulty: 'hard',
    question: 'Which nation has won the most Rugby World Cup titles (men’s)?',
    options: ['Australia', 'England', 'New Zealand', 'South Africa'],
    correctIndex: 3,
  },
  {
    id: 'sp-h03',
    category: 'sports',
    difficulty: 'hard',
    question: 'In the decathlon, how many events does an athlete compete in?',
    options: ['8', '9', '10', '12'],
    correctIndex: 2,
  },
  {
    id: 'sp-h04',
    category: 'sports',
    difficulty: 'hard',
    question: 'Which boxer was known as “The Greatest” and won gold in Rome 1960?',
    options: ['Joe Frazier', 'Muhammad Ali', 'George Foreman', 'Sonny Liston'],
    correctIndex: 1,
  },
  {
    id: 'sp-h05',
    category: 'sports',
    difficulty: 'hard',
    question: 'What is the diameter of a basketball hoop in inches (NBA/WNBA)?',
    options: ['16', '17', '18', '20'],
    correctIndex: 2,
  },
  {
    id: 'sp-h06',
    category: 'sports',
    difficulty: 'hard',
    question: 'Which city hosted the 1992 Summer Olympics?',
    options: ['Atlanta', 'Sydney', 'Barcelona', 'Athens'],
    correctIndex: 2,
  },
  {
    id: 'sp-h07',
    category: 'sports',
    difficulty: 'hard',
    question: 'In tennis, what is a score of 40–40 called?',
    options: ['Match point', 'Deuce', 'Advantage', 'Let'],
    correctIndex: 1,
  },
  {
    id: 'sp-h08',
    category: 'sports',
    difficulty: 'hard',
    question: 'Which NFL quarterback has the most career passing touchdowns (regular season, through 2023)?',
    options: ['Peyton Manning', 'Drew Brees', 'Tom Brady', 'Aaron Rodgers'],
    correctIndex: 2,
  },
  {
    id: 'sp-h09',
    category: 'sports',
    difficulty: 'hard',
    question: 'What is the regulation height of a basketball rim from the floor (feet)?',
    options: ['8', '9', '10', '11'],
    correctIndex: 2,
  },
  {
    id: 'sp-h10',
    category: 'sports',
    difficulty: 'hard',
    question: 'Which cyclist has the most Tour de France overall wins?',
    options: ['Miguel Indurain', 'Jacques Anquetil', 'Eddy Merckx', 'Bernard Hinault'],
    correctIndex: 2,
  },
];
